baseURL = '/'
languageCode = 'en-us'
title = 'Blockflare'
summaryLength = 10
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 5

[security]
enableInlineShortcodes = false
[security.http]
mediaTypes = ["application/json"]
methods = ["GET"]

[markup.highlight]
style = "friendly"
noClasses = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.extensions.typographer]
disable = false
apostrophe = '&apos;'
ellipsis = '&hellip;'
emDash = '&mdash;'
enDash = '&ndash;'
rightDoubleQuote = '&quot;'
leftDoubleQuote = '&quot;'
rightSingleQuote = '&apos;'
leftSingleQuote = '&apos;'
rightAngleQuote = '&rsaquo;'
leftAngleQuote = '&lsaquo;'

[params]
author = "Hanchin Hsieh"
avatar = 'https://avatars.githubusercontent.com/u/25029451?s=400&u=0c7eaf9379b7ce31bc02843a9568fac73a77cd8f&v=4'
desc = """AKA yuchanns, a developer with a passion for FOSS and a huge fan of LiSA (織部 里沙).
The creator and maintainer of the [Go Binding for Apache OpenDAL](https://github.com/apache/opendal/tree/main/bindings/go), and an [Emeritus](https://github.com/containerd/nerdctl/pull/3067) contributor to [nerdctl](https://github.com/containerd/nerdctl)."""
twitter = '_yuchanns_'
[params.pwa]
debug = true
[[params.pwa.precaches]]
url = "/"
[params.pwa.caches.image]
origins = ["oss.yuchanns.xyz", "avatars.githubusercontent.com", "blog.yuchanns.xyz"]
[params.pwa.caches.script]
origins = ["https://giscus.app", "blog.yuchanns.xyz"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"

[module]
[[module.imports]]
path = 'github.com/hugomods/pwa'

[outputs]
home = ['HTML', 'RSS', 'Offline', 'WebAppManifest']
